global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  group_by: [example, proxiaczki]

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#notifications'
    title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"