version: '3.3'
services:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx_status.conf:/etc/nginx/conf.d/default.conf

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.8.0
    ports:
      - 9113:9113
    command: -nginx.scrape-uri http://nginx/nginx_status


  grafana:
    image: grafana/grafana
    environment:
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
     - 3000:300

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093